name: spotify2youtube
description: Convert Spotify playlists to YouTube Music playlists.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.0
  flutter_appauth: ^6.0.4
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
