name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create new Flutter project
        run: |
          flutter create --org com.example --project-name spotify2youtube app_temp
          cp -r lib app_temp/
          cp pubspec.yaml app_temp/

      - name: Setup AppAuth Redirect Scheme in build.gradle
        run: |
          cd app_temp
          sed -i 's/defaultConfig {/defaultConfig {\n        manifestPlaceholders = [\n            "appAuthRedirectScheme": "spotify2youtube"\n        ]/' android/app/build.gradle

      - name: Install dependencies and Build APK
        run: |
          cd app_temp
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app_temp/build/app/outputs/flutter-apk/app-release.apk
